void readLUATableInit();
bool readLUATable(const char* filename, const char* vali_or_spec);
const char* getValiString();
const char* getSpecString();
bool getValidation(const char* specs);
const char* getValidationMessage();
const char* getValidationErrorParams();
bool getOutputSpecs(const char* specs);
const char* getOutputString();
int getNumberOfLines();
