outputFiles = {
    reactorState={
      filename="reactorState.txt",
      keys={
        y={
          pH={
            unit="[1]",
            col=4
          },
          COD={
            unit="[g/L]",
            col=3
          },
          FOS={
            unit="[g/L]",
            col=2
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    gammaValues={
      filename="dbg_gamma.txt",
      keys={
        y={
          hydro_Methanogenesis={
            unit="[]",
            col=5
          },
          aceto_Methanogenesis={
            unit="[]",
            col=9
          },
          Propionic_Degradation={
            unit="[]",
            col=4
          },
          Butyric_Degradation={
            unit="[]",
            col=7
          },
          Acidogenesis_LCFA={
            unit="[]",
            col=6
          },
          Valeric_Degradation={
            unit="[]",
            col=3
          },
          Acidogenesis_AA={
            unit="[]",
            col=8
          },
          Acidogenesis_MS={
            unit="[]",
            col=2
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    nitrogen={
      filename="dbg_nitrogenRates.txt",
      keys={
        y={
          SUM={
            unit="[g/L]",
            col=11
          },
          AA={
            unit="[g/L]",
            col=2
          },
          Nitrogen={
            unit="[g/L]",
            col=10
          },
          MO_hydroM={
            unit="[g/L]",
            col=5
          },
          MO_AcidoMS={
            unit="[g/L]",
            col=7
          },
          MO_Propionic={
            unit="[g/L]",
            col=9
          },
          MO_AcidoAA={
            unit="[g/L]",
            col=8
          },
          MO_AcidoLCFA={
            unit="[g/L]",
            col=3
          },
          MO_ButyricValeric={
            unit="[g/L]",
            col=4
          },
          MO_acetoM={
            unit="[g/L]",
            col=6
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    digestateConcentration={
      filename="digestateConcentrations.txt",
      keys={
        y={
          MS={
            unit="[g/L]",
            col=2
          },
          AA={
            unit="[g/L]",
            col=3
          },
          Butyric={
            unit="[g/L]",
            col=4
          },
          MO_ButyricValeric={
            unit="[g/L]",
            col=6
          },
          NH4N={
            unit="[g/L]",
            col=20
          },
          Acetic={
            unit="[g/L]",
            col=18
          },
          Nitrogen={
            unit="[g/L]",
            col=19
          },
          MO_hydroM={
            unit="[g/L]",
            col=9
          },
          Carbondioxide={
            unit="[g/L]",
            col=8
          },
          Hydrogen={
            unit="[g/L]",
            col=17
          },
          Propionic={
            unit="[g/L]",
            col=7
          },
          MO_Propionic={
            unit="[g/L]",
            col=16
          },
          LCFA={
            unit="[g/L]",
            col=12
          },
          MO_AcidoMS={
            unit="[g/L]",
            col=13
          },
          Methane={
            unit="[g/L]",
            col=14
          },
          Valeric={
            unit="[g/L]",
            col=10
          },
          MO_AcidoAA={
            unit="[g/L]",
            col=15
          },
          MO_AcidoLCFA={
            unit="[g/L]",
            col=5
          },
          MO_acetoM={
            unit="[g/L]",
            col=11
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    dbg_phContribution={
      filename="dbg_phContribution.txt",
      keys={
        y={
          Water={
            unit="-",
            col=8
          },
          Hions={
            unit="-",
            col=9
          },
          Nitrogen={
            unit="-",
            col=7
          },
          Butyric={
            unit="-",
            col=2
          },
          Valeric={
            unit="-",
            col=5
          },
          Carbondioxide={
            unit="-",
            col=4
          },
          Propionic={
            unit="-",
            col=3
          },
          Acetic={
            unit="-",
            col=6
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    reactionRates={
      filename="dbg_reactionrates.txt",
      keys={
        y={
          hydro_Methanogenesis={
            unit="[g/h]",
            col=5
          },
          aceto_Methanogenesis={
            unit="[g/h]",
            col=9
          },
          Propionic_Degradation={
            unit="[g/h]",
            col=4
          },
          Butyric_Degradation={
            unit="[g/h]",
            col=7
          },
          Acidogenesis_LCFA={
            unit="[g/h]",
            col=6
          },
          Valeric_Degradation={
            unit="[g/h]",
            col=3
          },
          Acidogenesis_AA={
            unit="[g/h]",
            col=8
          },
          Acidogenesis_MS={
            unit="[g/h]",
            col=2
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    vProdHourly={
      filename="producedNormVolumeHourly.txt",
      keys={
        y={
          Hydrogen={
            unit="[NL]",
            col=4
          },
          Carbondioxide={
            unit="[NL]",
            col=2
          },
          Sum={
            unit="[NL]",
            col=5
          },
          Methane={
            unit="[NL]",
            col=3
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    outflow={
      filename="outflow.txt",
      keys={
        y={
          MS={
            unit="[g/L]",
            col=3
          },
          ["All Liquid"]={
            unit="[L/h]",
            col=2
          },
          AA={
            unit="[g/L]",
            col=4
          },
          Butyric={
            unit="[g/L]",
            col=5
          },
          Propionic={
            unit="[g/L]",
            col=6
          },
          Valeric={
            unit="[g/L]",
            col=7
          },
          LCFA={
            unit="[g/L]",
            col=8
          },
          Acetic={
            unit="[g/L]",
            col=9
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    allMass={
      filename="subMO_mass.txt",
      keys={
        y={
          MS={
            unit="[g]",
            col=2
          },
          AA={
            unit="[g]",
            col=3
          },
          Butyric={
            unit="[g]",
            col=4
          },
          Methane_sum={
            unit="[g]",
            col=18
          },
          MO_ButyricValeric={
            unit="[g]",
            col=6
          },
          Acetic={
            unit="[g]",
            col=24
          },
          Hydrogen_sum={
            unit="[g]",
            col=23
          },
          MO_AcidoLCFA={
            unit="[g]",
            col=5
          },
          Hydrogen={
            unit="[g]",
            col=21
          },
          MO_Propionic={
            unit="[g]",
            col=20
          },
          MO_AcidoAA={
            unit="[g]",
            col=19
          },
          Carbondioxide_gas={
            unit="[g]",
            col=9
          },
          Carbondioxide={
            unit="[g]",
            col=8
          },
          Methane_gas={
            unit="[g]",
            col=17
          },
          Propionic={
            unit="[g]",
            col=7
          },
          Methane={
            unit="[g]",
            col=16
          },
          LCFA={
            unit="[g]",
            col=14
          },
          MO_AcidoMS={
            unit="[g]",
            col=15
          },
          Carbondioxide_sum={
            unit="[g]",
            col=10
          },
          Valeric={
            unit="[g]",
            col=12
          },
          MO_hydroM={
            unit="[g]",
            col=11
          },
          Hydrogen_gas={
            unit="[g]",
            col=22
          },
          MO_acetoM={
            unit="[g]",
            col=13
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    NormvolumeCumulative={
      filename="producedNormVolumeCumulative.txt",
      keys={
        y={
          Hydrogen={
            unit="[NL]",
            col=4
          },
          Carbondioxide={
            unit="[NL]",
            col=2
          },
          Sum={
            unit="[NL]",
            col=5
          },
          Methane={
            unit="[NL]",
            col=3
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    valveFlow={
      filename="valveGasFlow.txt",
      keys={
        y={
          Hydrogen={
            unit="[g/L/h]",
            col=4
          },
          Carbondioxide={
            unit="[g/L/h]",
            col=2
          },
          Methane={
            unit="[g/L/h]",
            col=3
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    avgEqValues={
      filename="dbg_avgEqValues.txt",
      keys={
        y={
          MS={
            unit="[1]",
            col=2
          },
          AA={
            unit="[1]",
            col=3
          },
          Butyric={
            unit="[1]",
            col=4
          },
          Phi={
            unit="[1]",
            col=22
          },
          MO_ButyricValeric={
            unit="[1]",
            col=6
          },
          Acetic={
            unit="[1]",
            col=21
          },
          MO_AcidoLCFA={
            unit="[1]",
            col=5
          },
          Hydrogen={
            unit="[1]",
            col=19
          },
          MO_Propionic={
            unit="[1]",
            col=18
          },
          Carbondioxide_gas={
            unit="[1]",
            col=9
          },
          Carbondioxide={
            unit="[1]",
            col=8
          },
          MO_AcidoAA={
            unit="[1]",
            col=17
          },
          Propionic={
            unit="[1]",
            col=7
          },
          Methane_gas={
            unit="[1]",
            col=16
          },
          LCFA={
            unit="[1]",
            col=13
          },
          MO_AcidoMS={
            unit="[1]",
            col=14
          },
          Methane={
            unit="[1]",
            col=15
          },
          Valeric={
            unit="[1]",
            col=11
          },
          MO_hydroM={
            unit="[1]",
            col=10
          },
          Hydrogen_gas={
            unit="[1]",
            col=20
          },
          MO_acetoM={
            unit="[1]",
            col=12
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    gasComposition={
      filename="gas_Volfraction.txt",
      keys={
        y={
          Hydrogen={
            unit="[vol%]",
            col=4
          },
          Carbondioxide={
            unit="[vol%]",
            col=2
          },
          Methane={
            unit="[vol%]",
            col=3
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    }
  }