outputFiles = {
    nitrogen={
      filename="dbg_nitrogenRates.txt",
      keys={
        y={
          SUM={
            unit="[g/L]",
            col=15
          },
          Proteins={
            unit="[g/L]",
            col=7
          },
          AA={
            unit="[g/L]",
            col=8
          },
          Nitrogen={
            unit="[g/L]",
            col=14
          },
          MO_hydroM={
            unit="[g/L]",
            col=6
          },
          Initial_Substrate={
            unit="[g/L]",
            col=3
          },
          MO_AcidoAA={
            unit="[g/L]",
            col=13
          },
          MO_ButyricValeric={
            unit="[g/L]",
            col=11
          },
          MO_AcidoMS={
            unit="[g/L]",
            col=12
          },
          MO_Propionic={
            unit="[g/L]",
            col=10
          },
          Substrate={
            unit="[g/L]",
            col=4
          },
          MO_AcidoLCFA={
            unit="[g/L]",
            col=5
          },
          Lignin={
            unit="[g/L]",
            col=2
          },
          MO_acetoM={
            unit="[g/L]",
            col=9
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    digestateConcentration={
      filename="digestateConcentrations.txt",
      keys={
        y={
          MS={
            unit="[g/L]",
            col=2
          },
          AA={
            unit="[g/L]",
            col=11
          },
          Butyric={
            unit="[g/L]",
            col=4
          },
          Initial_Substrate={
            unit="[g/L]",
            col=5
          },
          Carbohydrates={
            unit="[g/L]",
            col=6
          },
          Substrate={
            unit="[g/L]",
            col=7
          },
          MO_AcidoLCFA={
            unit="[g/L]",
            col=8
          },
          NH4N={
            unit="[g/L]",
            col=26
          },
          Lipids={
            unit="[g/L]",
            col=22
          },
          Acetic={
            unit="[g/L]",
            col=24
          },
          Proteins={
            unit="[g/L]",
            col=10
          },
          MO_AcidoAA={
            unit="[g/L]",
            col=23
          },
          Nitrogen={
            unit="[g/L]",
            col=25
          },
          Propionic={
            unit="[g/L]",
            col=13
          },
          Carbondioxide={
            unit="[g/L]",
            col=14
          },
          Hydrogen={
            unit="[g/L]",
            col=21
          },
          MO_hydroM={
            unit="[g/L]",
            col=9
          },
          Lignin={
            unit="[g/L]",
            col=3
          },
          LCFA={
            unit="[g/L]",
            col=18
          },
          MO_AcidoMS={
            unit="[g/L]",
            col=19
          },
          Methane={
            unit="[g/L]",
            col=20
          },
          Valeric={
            unit="[g/L]",
            col=17
          },
          MO_ButyricValeric={
            unit="[g/L]",
            col=16
          },
          MO_Propionic={
            unit="[g/L]",
            col=15
          },
          MO_acetoM={
            unit="[g/L]",
            col=12
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    dbg_phContribution={
      filename="dbg_phContribution.txt",
      keys={
        y={
          Water={
            unit="-",
            col=8
          },
          Hions={
            unit="-",
            col=9
          },
          Nitrogen={
            unit="-",
            col=7
          },
          Butyric={
            unit="-",
            col=2
          },
          Valeric={
            unit="-",
            col=5
          },
          Carbondioxide={
            unit="-",
            col=4
          },
          Propionic={
            unit="-",
            col=3
          },
          Acetic={
            unit="-",
            col=6
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    reactionRates_integrated={
      filename="dbg_reactionrates_integrated.txt",
      keys={
        y={
          hydro_Methanogenesis={
            unit="[g/h]",
            col=2
          },
          Disintegration_Initial={
            unit="[g/h]",
            col=3
          },
          Hydrolysis_Proteins={
            unit="[g/h]",
            col=4
          },
          aceto_Methanogenesis={
            unit="[g/h]",
            col=5
          },
          Valeric_Degradation={
            unit="[g/h]",
            col=6
          },
          Acidogenesis_MS={
            unit="[g/h]",
            col=7
          },
          Disintegration_Substrate={
            unit="[g/h]",
            col=8
          },
          Propionic_Degradation={
            unit="[g/h]",
            col=9
          },
          Acidogenesis_LCFA={
            unit="[g/h]",
            col=14
          },
          Hydrolysis_Lipids={
            unit="[g/h]",
            col=11
          },
          Hydrolysis_Carbohydrates={
            unit="[g/h]",
            col=12
          },
          Acidogenesis_AA={
            unit="[g/h]",
            col=13
          },
          Butyric_Degradation={
            unit="[g/h]",
            col=10
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    vProdHourly={
      filename="producedNormVolumeHourly.txt",
      keys={
        y={
          Hydrogen={
            unit="[NL]",
            col=4
          },
          Carbondioxide={
            unit="[NL]",
            col=2
          },
          Sum={
            unit="[NL]",
            col=5
          },
          Methane={
            unit="[NL]",
            col=3
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    outflow_integrated={
      filename="outflow_integrated.txt",
      keys={
        y={
          MS={
            unit="[g/L]",
            col=3
          },
          ["All Liquid"]={
            unit="[L/h]",
            col=2
          },
          AA={
            unit="[g/L]",
            col=5
          },
          Butyric={
            unit="[g/L]",
            col=4
          },
          Propionic={
            unit="[g/L]",
            col=6
          },
          Valeric={
            unit="[g/L]",
            col=7
          },
          LCFA={
            unit="[g/L]",
            col=8
          },
          Acetic={
            unit="[g/L]",
            col=9
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    allMass={
      filename="subMO_mass.txt",
      keys={
        y={
          MS={
            unit="[g]",
            col=2
          },
          AA={
            unit="[g]",
            col=11
          },
          Butyric={
            unit="[g]",
            col=4
          },
          Initial_Substrate={
            unit="[g]",
            col=5
          },
          Acetic={
            unit="[g]",
            col=30
          },
          Carbohydrates={
            unit="[g]",
            col=6
          },
          MO_AcidoAA={
            unit="[g]",
            col=29
          },
          Lipids={
            unit="[g]",
            col=28
          },
          Hydrogen_sum={
            unit="[g]",
            col=27
          },
          Substrate={
            unit="[g]",
            col=7
          },
          MO_AcidoLCFA={
            unit="[g]",
            col=8
          },
          Propionic={
            unit="[g]",
            col=13
          },
          Hydrogen={
            unit="[g]",
            col=25
          },
          Methane_sum={
            unit="[g]",
            col=24
          },
          Proteins={
            unit="[g]",
            col=10
          },
          Methane_gas={
            unit="[g]",
            col=23
          },
          Methane={
            unit="[g]",
            col=22
          },
          Carbondioxide_gas={
            unit="[g]",
            col=15
          },
          Carbondioxide={
            unit="[g]",
            col=14
          },
          Lignin={
            unit="[g]",
            col=3
          },
          MO_ButyricValeric={
            unit="[g]",
            col=18
          },
          MO_hydroM={
            unit="[g]",
            col=9
          },
          LCFA={
            unit="[g]",
            col=20
          },
          MO_AcidoMS={
            unit="[g]",
            col=21
          },
          Carbondioxide_sum={
            unit="[g]",
            col=16
          },
          Valeric={
            unit="[g]",
            col=19
          },
          MO_Propionic={
            unit="[g]",
            col=17
          },
          Hydrogen_gas={
            unit="[g]",
            col=26
          },
          MO_acetoM={
            unit="[g]",
            col=12
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    NormvolumeCumulative={
      filename="producedNormVolumeCumulative.txt",
      keys={
        y={
          Hydrogen={
            unit="[NL]",
            col=4
          },
          Carbondioxide={
            unit="[NL]",
            col=2
          },
          Sum={
            unit="[NL]",
            col=5
          },
          Methane={
            unit="[NL]",
            col=3
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    valveFlow={
      filename="valveGasFlow.txt",
      keys={
        y={
          Hydrogen={
            unit="[g/L/h]",
            col=4
          },
          Carbondioxide={
            unit="[g/L/h]",
            col=2
          },
          Methane={
            unit="[g/L/h]",
            col=3
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    }
}
