outputFiles = {
    allMass={
      filename="subMO_mass.txt",
      keys={
        y={
          Lignin={
            unit="[g]",
            col=2
          },
          Carbondioxide_gas={
            unit="[g]",
            col=8
          },
          Carbondioxide={
            unit="[g]",
            col=7
          },
          Acetic={
            unit="[g]",
            col=11
          },
          Methane_sum={
            unit="[g]",
            col=5
          },
          Methane_gas={
            unit="[g]",
            col=4
          },
          Substrate={
            unit="[g]",
            col=6
          },
          Carbondioxide_sum={
            unit="[g]",
            col=9
          },
          Methane={
            unit="[g]",
            col=3
          },
          MO_acetoM={
            unit="[g]",
            col=10
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    dbg_phContribution={
      filename="dbg_phContribution.txt",
      keys={
        y={
          Water={
            unit="-",
            col=5
          },
          Hions={
            unit="-",
            col=6
          },
          Nitrogen={
            unit="-",
            col=4
          },
          Carbondioxide={
            unit="-",
            col=2
          },
          Acetic={
            unit="-",
            col=3
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    nitrogen={
      filename="dbg_nitrogenRates.txt",
      keys={
        y={
          SUM={
            unit="[g/L]",
            col=6
          },
          Lignin={
            unit="[g/L]",
            col=2
          },
          Nitrogen={
            unit="[g/L]",
            col=5
          },
          Substrate={
            unit="[g/L]",
            col=3
          },
          MO_acetoM={
            unit="[g/L]",
            col=4
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    digestateConcentration={
      filename="digestateConcentrations.txt",
      keys={
        y={
          Nitrogen={
            unit="[g/L]",
            col=8
          },
          Lignin={
            unit="[g/L]",
            col=2
          },
          Methane={
            unit="[g/L]",
            col=3
          },
          Substrate={
            unit="[g/L]",
            col=4
          },
          Carbondioxide={
            unit="[g/L]",
            col=5
          },
          Acetic={
            unit="[g/L]",
            col=7
          },
          MO_acetoM={
            unit="[g/L]",
            col=6
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    reactionRates={
      filename="dbg_reactionrates.txt",
      keys={
        y={
          simpleHydrolysis={
            unit="[g/h]",
            col=2
          },
          aceto_Methanogenesis={
            unit="[g/h]",
            col=3
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    vProdHourly={
      filename="producedNormVolumeHourly.txt",
      keys={
        y={
          Carbondioxide={
            unit="[NL]",
            col=3
          },
          Sum={
            unit="[NL]",
            col=4
          },
          Methane={
            unit="[NL]",
            col=2
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    reactorState={
      filename="reactorState.txt",
      keys={
        y={
          pH={
            unit="[1]",
            col=4
          },
          COD={
            unit="[g/L]",
            col=3
          },
          FOS={
            unit="[g/L]",
            col=2
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    NormvolumeCumulative={
      filename="producedNormVolumeCumulative.txt",
      keys={
        y={
          Carbondioxide={
            unit="[NL]",
            col=3
          },
          Sum={
            unit="[NL]",
            col=4
          },
          Methane={
            unit="[NL]",
            col=2
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    valveFlow={
      filename="valveGasFlow.txt",
      keys={
        y={
          Carbondioxide={
            unit="[g/L/h]",
            col=3
          },
          Methane={
            unit="[g/L/h]",
            col=2
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    avgEqValues={
      filename="dbg_avgEqValues.txt",
      keys={
        y={
          Lignin={
            unit="[1]",
            col=2
          },
          Carbondioxide_gas={
            unit="[1]",
            col=7
          },
          Carbondioxide={
            unit="[1]",
            col=6
          },
          Phi={
            unit="[1]",
            col=10
          },
          Methane={
            unit="[1]",
            col=3
          },
          Substrate={
            unit="[1]",
            col=5
          },
          Acetic={
            unit="[1]",
            col=9
          },
          Methane_gas={
            unit="[1]",
            col=4
          },
          MO_acetoM={
            unit="[1]",
            col=8
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    },
    gasComposition={
      filename="gas_Volfraction.txt",
      keys={
        y={
          Carbondioxide={
            unit="[vol%]",
            col=3
          },
          Methane={
            unit="[vol%]",
            col=2
          }
        },
        type="CSV",
        comment="#",
        delimiter="\t",
        x={
          Time={
            unit="[h]",
            col=1
          }
        }
      }
    }
  }
